[package]
name = "sniffer"
version = "0.1.0"
authors = ["sq5rix <sq5rix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33"}